spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fitapidb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:fitapi}
    password: ${DB_PASSWORD:fitapi}
